language: php

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./bin/phpcs src --standard=psr2-override.xml
  - ./bin/phpspec r
