language: php

services:
  - docker

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./bin/phpcs -p --standard=psr2-override.xml src
  - composer test
