language: php

services:
  - docker

before_install:
  - docker build -t nigelgreenway/reactive_slim .
  - docker run -d -p 1351:1351 --name reactive_slim nigelgreenway/reactive-slim

after_install:
  - docker stop reactive_slim
  - docker rm reactive_slim

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./bin/phpcs src --standard=psr2-override.xml
  - ./bin/phpspec r
