language: php

services:
  - docker

after_install:
  - docker stop reactive_slim
  - docker rm reactive_slim

php:
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - ./bin/phpcs src --standard=psr2-override.xml
  - ./bin/phpspec r
  - ./bin/phpunit -c ./test/phpunit.xml.dist ./test/
